INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (1, '当倒车时,你应该', '检查两边侧视镜', '查看所有后视镜', '转⾝向后玻璃观望', '看后视镜 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (2, '在上斜坡停车于⼤型车辆后⾯要多留下空位原因是', '你可被前⾯的车辆看见', '你不会呼吸到卡车排出的废⽓ ', '在它起步慢的时候,你可以绕过它', '⼤型车辆在起步时会滑后撞倒你的车', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (3, '如果后⾯车辆跟你太近,保护你的最佳⽅法是', '增加车前的空间', '增加车后的空间 ', '响喇叭以及闪亮刹车灯', '急刹车然后尽快离去', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (4, '此标志意思是', '慢⾏车辆', '你有道路优先权 ', '让道路优先权于其他⼈ ', '残疾⼈⼠车辆 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (5, '驾驶员对骑⾃⾏车⼈响喇叭是因为', '告诉骑⾃⾏车⼈他已在附近', '给予警告', '告诉骑⾃⾏车⼈让路 ', '告诉骑⾃⾏车⼈附近有车辆', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (6, '红灯持久亮着意思是', '停车,安全时向前', '停车,右转弯除外', '在⼗字路口之前停车 ', '如有车辆靠近停车 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (7, '此标志意思是', '前⾯是弯路 ', '前⾯可能有滑溜的路⾯ ', '回旋弯路', '准备前⾯突然停车', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (8, '下列哪⼀辆车在转弯时最容易失控', '车辆b ', '车辆d ', '车辆 c ', '车辆a ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (9, '在双线路上,避免意外发⽣最不安全的做法是 ', '把脚离开油门 ', '转到左线 ', '⽤⼒刹车⽽不锁死刹车制', '闪亮车头灯和响喇叭提醒其他驾驶者 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (10, '附近有⼉童在玩耍,你应该', '减速并随时准备停车', '驶到路旁停车,直到⼩孩离开 ', '转到左线并保持速度 ', '响喇叭和保持速度', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (11, '此标志意思是', '⼗字路口只可以左转', '前⾯路口不准左转', '前⾯⽆路,左转', '此⾏车道不准左转', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (12, '你与⼀位负责驾驶的朋友外出,⽽他不停喝酒,你最不安全的做法是', '告诉他为什么不能开车', '告诉他乘计程车和公共汽车或打电话给朋友', '拿⾛他的车钥匙', '确保他开慢车', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (13, '此驾驶员在转弯之前,他应该', '慢车以及闪亮他的车头灯', '保持速度并在路口做180度查看', '回头看并在路口做180度查看', '靠左及看侧视镜', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (14, '有⼀辆车在双线路上准备超越时,你应该', '继续保持速度和⾏车位置', '加速和靠右', '靠右并保持速度', '准备慢车并预留空位 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (15, '如何应付路霸的侵略性⾏为?', '找公⽤电话报警 ', '直接开车回家', '把车开到⼈群多的地⽅', '响喇叭和呼喝他 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (16, '要超越⼀辆⾃⾏车时,你应该', '预留更多的空间', '保持你的⾏车位置 ', '与它保持⼀公尺的空间', '响喇叭⽰意你要越过他', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (17, '在加速线上,a车驾驶员⾸先应该', '慢车等待空间 ', '停车等待空间', '观察交通情况 ', '加速并配合路上的车辆 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (18, '在下雪天要安全驾驶,你应该', '每次看到危险时要刹车', '确保你的车辆已维修好', '亮起远光灯  ', '预留更多的空间', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (19, '禁⽌U形掉头', '在弯路或坡顶以及视线受阻的地⽅', '在住宅区 ', '在⽆交能信号的路⼜', '在公众停车场内 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (20, '跟随消防车,你最少离它', '50公尺', '180公尺', '150公尺', '60公尺', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (21, '图中的车辆同时到达停车标志,谁应该先⾏? ', '车辆a ', '车辆b ', '⽆论是谁先抵达路口', '两部车可同时⾏驶', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (22, '跟随摩托车时,你应该', '保持更远的距离', '亮起你的车头灯', '把脚放在刹车上', '慢速⾏驶', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (23, '在红灯时,你何时可以右转? ', '当没有车辆的时候', '在完全停车后和没有禁⽌转弯标志的情况下 ', '当没有标志此转弯的时候', '只可以在紧急情况下', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (24, '眼神接触是⽤来', '警告他⼈你有道路优先权', '给予他⼈道路优先权', '告诉他们你不满他们的做法 ', '表⽰你已经看见他们 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (25, '要⿎励你的朋友安全开车最好⽅法是 ', '坚持他们低速⾏车', '提醒他们所犯的错误 ', '告诉他们你的做法 ', '在他们开得好的进侯表扬⼀番', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (26, '哪⼀辆车在e车的盲点内? ', '车辆a', '车辆b', '车辆c', '车辆d', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (27, '超越摩托车要多留空间的原因是 ', '他⽐车辆更轻   ', '骑摩托车⼈没有开车⼈的技术好', '因为他们经常开得快 ', '汽车会把脏东西溅到摩托车司机的⾝上', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (28, '车辆a先到停车标志,谁应让路? ', '任何先到路口的车辆 ', '车辆b ', '两部车可以同时⾏驶', '车辆a', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (29, '在繁忙的市区驾驶者应与⾃⾏车保持更远的空间,是因为 ', '很难看见他们的⼿势', '骑⾃⾏车的⼈太慢', '他们在转弯的时候要穿过多条车道很不容易', '骑⾃⾏车的⼈在路口常在车辆间穿插 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (30, '在红灯下⾯的绿箭头闪动时, 你应该 ', '随时可以左转 ', '在左转之前等待红灯转为绿灯 ', '任何时候不可以左转', '左转 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (31, '恶劣天⽓影响视线情况下,你应该 ', '保持速度并叫你的乘客提配危险', '亮起远光灯', '闪动紧急灯号 ', '慢车以及亮着近光灯 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (32, '交通灯刚转为绿灯,摩托车⾯临的危险是什么?', '摩托车后⾯的车辆b可能会撞到他 ', '车辆a可能在路⼜打滑 ', '车辆a驾驶员在左转时可能看不见他撞倒他 ', '摩托车可能在⾬中打滑 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (33, '此标志意思是', '有⼯⼈和机械在进⾏施⼯你必须遵守标志上的限速 ', '有⼯⼈和机械在进⾏施⼯你必须遵守标志上的限速只限⽩天', '你必须遵守标志上的限速如果看见有⼯⼈在路上', '前⾯有障碍 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (34, '此标志意思是', '前⾯是⽔泥路⾯   ', '前⾯路不平坦 ', '前⾯柏油路⾯终⽌', '⼩⼼路上的⽯块 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (35, '⼤部分撞车尾可以避免,如果驾驶者', '保持更远的距离', '加速反应 ', '加快速度', '减慢速度 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (36, '⼀个负责任的驾驶员', '告诉其他驾驶者他们的错误', '应考虑所有道路使⽤者的安全', '确保你和你的乘客的安全', '确保能够受到其他⼈的尊敬 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (37, '路上的卡车为何要停车? ', '因为⾏⼈道上有⼈', '由于卡车要转弯 ', '卡车的驾驶同迷路要看地图 ', '卡车的驾驶员要停车', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (38, '你不应该超越车辆', '有松⼟路边的警告时', '在弯路上 ', '在他慢速的时候   ', '当你那边是虚线 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (39, '在没有标明情况下,最⾼限速是', '市区60公⾥和郊区80公⾥', '市区50公⾥和郊区80公⾥', '市区50公⾥和郊区90公⾥', '市区60公⾥和郊区90公⾥', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (40, '此标志意思是', '附近有运动场,⼩⼼驾驶 ', '运动场过路线停车让⾏⼈过马路 ', '时速30公⾥每天黎明到黄错', '时速30公⾥从早上8点到下午5点在上课⽇⼦⾥ ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (41, '下列哪⼀项不是醉酒的迹象?', '反应更快 ', '对周围失去感觉 ', '眼睛凝视', '视程减低 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (42, '当你要驶⼊交通道路时,你应该 ', '在来车距离低于两公尺时必须让路', '⽤⼿号 ', '让路给已在交通的车辆 ', '有道路优先权 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (43, '当正在⾼速⾏驶时,前⾯突然要转弯,最好的处理⽅法是 ', '在进弯前把脚离开油门', '在进弯后刹车', '在进弯时刹车', '保持速度以及紧握⽅向盘', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (44, '头枕中部的⾼度应该在 ', '你的颈部', '不低于你的⽿尖 ', '跟你的头项平⾏', '任何舒适的位置 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (45, '当你要进⼊环形交叉路口时,你必须', '让任何已在环形交叉路口内的车辆', '顺时针⽅向在环形岛路口⾏驶', '在进⼊时保持速度 ', '在进⼊时亮着⽅向灯', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (46, '要保持正确的⾏车位置,最佳⽅法是', '看着你侧边的车辆并保持与他们的距离 ', '紧握⽅向盘 ', '向着你去路⽅向的远处看', '直接看着你前⾯的车辆 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (47, '当你到达⼀个有闪动红灯路口时,你必须', '像看到停车标志⼀样停车 ', '等待红灯转为绿灯 ', '慢下来让路 ', '慢驶以及⼩⼼向前 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (48, '⾏驶所标明的最⾼限速应该是', '在理想情况下', '在⽩天 ', '超车除外', '在视野⽋佳的情况下 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (49, '图中的哪⼀段路在后视镜不容易看见? ', '路段a', '路段c ', '路段d  ', '路段b ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (50, '两部迎⾯⽽来的车辆同时到达⼀个⽆控制的⼗字路口时', '左转车辆必须让路', '后到路⼜的车辆必须让路 ', '直⾏车辆必须让路 ', '右转车辆必须让路', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (51, '要防备他⼈做出意料之外的⾏为,最佳⽅法是', '把⼿放在喇叭上 ', '预留更⼤的空间停车和可能绕过车辆 ', '低于限速⾏驶', '坚持道路优先权 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (52, '图中的车辆必须停在', '⼗字路口', '离开⼗字路口⼀公尺', '马路上的⽩线之前', '当驾驶者看到路口情况', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (53, '闪动的绿灯是 ', '你可以在绿灯下继续⾏驶', '迎⾯车辆正⾯对红灯', '交通灯号由⾏⼈控制', '此灯号将快转为红灯', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (54, '尾随卡车太近最⼤的危险是', '卡车会阻碍你的视线看不清前⾯的情况', '其他驾驶者可能看不见你在⼤型车辆后⾯', '⽓流可能会影响你控制⽅向盘', '⼤型车辆可能会突然转线 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (55, '在下斜坡时使⽤空档', '是省油的好⽅法', '对经验丰富的⼈⽐较安全 ', '会伤害齿轮', '不合法和不安全 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (56, '下列哪⼀项能帮助你酒后清醒? ', '时间', '新鲜空⽓', '咖啡', '运动', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (57, '当绿灯时,要左转司机应该 ', '尽快转离路口', '有道路优先权', '必须让路于迎⾯车辆直到有⼀个安全的空隙才转弯 ', '等待所有车辆都已通过', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (58, '哪⼀辆车没有安全的空隙驶往路边? ', '车辆a', '车辆b', '车辆d', '车辆c', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (59, '这个放在⾏车道上的信号灯,意思是 ', '此⾏车道在建筑⼯程中', '禁⽌在此车道⾏驶 ', '此车道将要终⽌,尽快离开 ', '此车道将快加⼊使⽤ ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (60, '在有让路标志路⼜,驾驶者应该 ', '将车辆完全停下来 ', '让路于要横过的车辆 ', '让路给所有的车辆,包括⾃⾏车和⾏⼈ ', '让路于横过马路的⾏⼈ ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (61, '此标志意思是', '禁⽌卡车通⾏', '驾驶者应⼩⼼⾼速⾏驶的卡车 ', '前⾯有卡车或⼯程车横过 ', '卡车只能在超车道⾏驶', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (62, '驾驶者可以使⽤⾃⾏车道 ', '当没有⾃⾏车时', '当超车时 ', '在路边泊车时 ', '在右转时 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (63, '车辆a驾驶员应该 ', '保持速度并脚踏刹车 ', '停车直到卡车完全转弯 ', '响喇叭告诉卡车他在附近 ', '慢车并观察卡车有可能转⼤弯 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (64, '你什么时候必须遵守标志牌上的限速? ', '每天上午时⾄下午时 ', '在上课天所有时间 ', '在上课天上午8时⾄下午5时 ', '任何时间 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (65, '你何时可以获准超过标志牌的限速⾏驶? ', '在⾼速公路上 ', '永远不可以 ', '当⽩天和天⽓良好的情况下 ', '当你要追上车流的时候 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (66, '此标志意思是', '前⾯⾏车道变窄', '交通汇合处', '前⾯有车辆汇⼊', '前⾯有⼗字路⼜口', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (67, '晴天在⾼速公路上⾏驶,你与前车最少要保持多少距离? ', '8秒', '10秒', ' 3秒', ' 6秒 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (68, '当四辆车驶近⼀个四道停车路口,驾驶者必须让道优先权给 ', '在你右⽅的车辆 ', '第⼀部到路口⽽停过车的车辆 ', '转右的车辆 ', '左⽅的车 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (69, '图中车辆a将要右转,他应该留意的危险是什么? ', '从后⾯上来的⾃⾏车', '从左边超车的b车 ', '从停泊车辆的空隙间⾛出来的狗或其他动物 ', '在⾏⼈道上的⾏⼈', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (70, '此标志的意思是', '你有道路优先权 ', '前⾯不准转道 ', '前⾯是单程路 ', '前⾯路口不准转弯 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (71, '你必须亮起车头灯,在能见度低于? ', ' 200公尺', '250公尺 ', '150公尺 ', '300公尺 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (72, '紧急灯是', '在⾼速公路上容易让其他驾驶者看见', '在泊车时应该亮着', '告诉其他驾驶者在接近已停下的车辆时要⼩⼼  ', '在慢速⾏车时必须亮起 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (73, ' HOV车道只适⽤于', '公交车和和限定⼈数车辆或摩托车和⾃⾏车   ', '⽕车(卡车) ', '紧急车辆  ', '繁忙时间 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (74, '两辆车同时抵达路口, 谁该先⾏? ', '⽆论哪辆车已停下,另⼀辆该先⾏ ', '直⾏车辆 ', '亮起左⽅向灯的车辆', '已经做好准备的车辆 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (75, '以60公⾥时速撞向其它车辆,车内⼈员受伤程度如同⼏层楼顶掉下? ', '4层', '1层', '2层', '3层', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (76, '当⼀辆学校巴⼠停在路边闪着红灯时,你必须停车 ', '⽆论你是来⾃迎⾯或跟随后⾯   ', '你来⾃迎⾯以及中间有安全岛的地⽅ ', '只是学校巴⼠在你前⾯的时候', '迎⾯来的车辆⽐跟随的车辆更重要 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (77, '此标志意思是 ', '前⾯是向右弯道    ', '单程道靠右⾏驶 ', '前⾯有障碍,靠左       ', '前⾯有障碍,靠右 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (78, '朋友开车太快,要让他知道你的想法最好是说: ', '你有没有看到速度标志牌      ', '你速度使我觉得很不舒服 ', '你⽐所标明的速度太快', '你为什么常开快车 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (79, '图中哪⼀个握⽅向的位置是最正确? ', '图a', '图d', '图b', '图c', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (80, '此驾驶员应该', '移到⾃⾏车的后⾯', '在⾃⾏车侧边⾏驶让它看见他要转弯 ', '响喇叭警告骑⾃⾏车的⼈他要转弯 ', '等待⾃⾏车已离开路⼜才转弯', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (81, '当铁路交叉路口的红灯闪动时,你必须', '慢车⼩⼼穿过', '停车,在通过前观察两边', '停车,看到绿灯时通过 ', '停车,等红灯完全熄灭以及安全情况下通过 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (82, '此标志意思是 ', '允许右转和左转', '允许在左边或右边泊车', '前⾯有障碍,向着箭头所指⽅向慢驶', '前⾯修路,掉头 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (83, '⿊冰是怎样形成? ', '路上的⽔冻结⽽成 ', '因为多层积雪 ', '在阴暗地⽅的硬雪 ', '冰雪太脏不容易看见 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (84, '下列哪⼀项与喝酒⽆关? ', '反应⽐较慢 ', '难与他⼈配合', '更加冲动', '由于放松开得更好 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (85, '在市区开车驾驶者应向前扫描最少 ', '8秒', '15秒', '5秒', '12秒 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (86, '正在路边骑⾃⾏车的⼈所⾯临的危险是什么? ', '⾏⼈会突然站在骑⾃⾏车⼈的⾯前 ', 'b车驾驶员可能会开到骑⾃⾏车⼈的后⾯', 'a车驾驶员在慢驶和转弯时,⾃⾏车有可能骑到他后⾯', 'a车驾驶员在转弯时有可能看不见⾃⾏车', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (87, '在进⼊⾼速公路时,驾驶员应怎样查看交通情况?', '查看后视镜', '查看侧视镜和后视镜以及看盲点 ', '看盲点和加快速度', '停车,然后看盲点', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (88, '要确保看到盲点内的东西,最好⽅法是', '在转弯或换线前回头看', '做180度检查 ', '让乘客替你查看  ', '确保常看后视镜 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (89, '当你驶⾄⼀个交通灯失灵的⼗字路口,你应该', '视同⼀个四道停车的路口处理', '如果有空间就通过', '当另外⼀个驾驶员挥⼿时通过', '等待交通指挥贺来指挥 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (90, '骑⾃⾏车的有权 ', '不在停车标志停车', '反⽅向⾏驶', '在右转道遇到不安全的时候移到车道中间', '不服从交通指挥员的指⽰', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (91, '驾驶此车辆的驾驶员应该 ', '慢驶,在接近路口之前脚踏刹车制 ', '在接近路口之前停车和让路', '保持速度并查看路口的其他车辆 ', '在近路口之前慢下来 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (92, '⼀个持着⽩⾊拐杖的⼈在过马路时,你应该 ', '⼩⼼并让出更多的空间', '响喇叭警告他附近有车辆 ', '停车并伸出窗外喊他过马路 ', '视同其他⾏⼈⼀样 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (93, '此标志意思是', '所有车辆必须在前⾯左转', '此⾏车道必须左转或右转', '双程左转车道', '⼗字路口只准左转 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (94, '在此标志上你会看到什么速度', '时速20公⾥', '时速25公⾥', '时速30公⾥', '时速35公⾥', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (95, '你永远不应该超越⼀辆车', '在接近坡顶时 ', '在滂沱⼤⾬天', '在夜间的双线路上', '在不熟悉的道路', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (96, '此标志意思是', '此⾏车道必须在前⾯右转 ', '慢驶,前⾯有向右的急转弯 ', '⼗字路口只准右转', '前⾯向右回转 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (97, '在夜间驾驶你特别要留意⾏⼈和⾃⾏车,原因是', '他们在夜间不太遵守交通规则', '⾃⾏车辆更多 ', '他们不容易被看见', '他们有可能不太⼩⼼', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (98, '当⼗字路口交通灯转为黄⾊时,你必须', '停车', '减慢速度', '⼩⼼向前 ', '停车,除⾮当时不安全 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (99, '车辆打滑时你的最佳反应是 ', '离开油门,把⽅向盘扭向你要去的⽅向', '离开油门并向反⽅向扭⽅盘 ', '刹车并顺着打滑的⽅向扭⽅向盘', '向着打滑的反⽅向扭⽅向盘 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (100, '饮⽤酒精⼈⼠,他们会错误认为 ', '很容易发怒 ', '他们神志反应敏捷 ', '他们⾏动缓慢', '他们的集中⼒降低 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (101, '当该⽼⼈踏上⾏⼈道时,此驾驶员应该', '继续⾏驶除⾮她已经在车辆⾯前', '挥⼿叫她横过', '以眼神让她知道并等她横过马路 ', '响喇叭告诉她继续横过马路 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (102, '下列哪⼀项对处理来⾃朋党负⾯影响的做法不适宜? ', '呆想—我的表现对他们看来是否太笨', '认识错误 ', '回想过程', '认识转机 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (103, '此标志意思是', '前⾯必须靠右', '前⾯是双程交通', '前⾯右边⾏车道终⽌', '前⾯有狭窄建筑物 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (104, '驾驶员应考虑到最危险的是', '任何可能造成伤害的驾驶环境', '路上的其他车辆 ', '违反交通规则的驾驶员', '恶劣天⽓环境 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (105, '此车辆驾驶员应该 ', '闪动远光灯,告诉⾃⾏车离开', '快速绕过⾃⾏车 ', '响喇叭告诉⾃⾏车离开 ', '等待车辆和⾃⾏车过了弯路之后才超车 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (106, '此驾驶员必须 ', '停车,告诉⾏⼈她不能在此横过马路 ', '让⾏⼈横过马路', '继续⾏驶因为此处没有⾏⼈过路线 ', '停车挥⼿⽰意⾏⼈横过马路 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (107, '转向灯应该 ', '在交通繁忙时亮起 ', '在⼀条街口之前亮起', '只是在街⾓转弯时亮起', '在每次转弯或转换⾏车道时亮起 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (108, '固定绿箭头意思是 ', '在完全停车后,你可以向箭头⽅向转弯 ', '见⾯街道是单程道 ', '在⼗字路口清晰情况下你可以向箭头⽅向转弯 ', '在⼗字路口你只可以左转', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (109, '处理⼀个有侵略性⾏为的驾驶员,最好的⽅法是', '跟上去告诉他你是不可以欺负', '给予他们更⼤的空间和道路优先权', '响喇叭⽰意他们你并不欣赏他们的恶劣态度 ', '坚持你有道路优先权 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (110, '此骑⾃⾏车的⼈所⾯临的危险是什么? ', '停泊在对⾯马路的车辆在开启时会撞到她 ', '路上后车的车辆 ', '她可能歪倒撞到停泊在路旁的车辆 ', '车⾥的⼈可能随时打开车门撞倒她 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (111, '此标志意思是 ', '学校范围,⼩⼼附近学童和⾏⼈ ', '学校范围减速⾄时速30公⾥', '前⾯有⾏⼈横过马路', '前⾯是学校过路线', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (112, '如果你的车辆发⽣故障,你应该', '停在你的⾏车道,并亮起应急灯号 ', '驶⾄路旁并亮起应急灯号 ', '减速开⾄下⼀个出口 ', '响喇叭并开⾄下⼀个路口', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (113, 'a车驾驶员最应留意的是', '路上的球,因⼩孩会追随它', '该车后⾯的车辆 ', '在⾏⼈道上的⾏⼈', '迎⾯来的车辆 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (114, '⽔⾯滑⾏的危险性增加是因为 ', '车辆在上坡', '车辆太重', '已换上雪胎 ', '轮胎太旧线纹太浅 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (115, '你什么时候特别要查看后视镜 ', '在减速和准备停车时', '在准备加速时 ', '在到后泊车时 ', '在停车标起步时', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (116, '图中a车驾驶员应该 ', '停车,告诉⾏⼈他不应该在这⾥过马路', '停车让⾏⼈横过马路', '应该继续⾏驶因为那⾥没有过路线', '必须停车和挥⼿叫⾏⼈过马路', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (117, '在接近⼀个绿灯已经亮了很久的路口,你应该 ', '准备停车', '查看交通情况,如没有车辆加速', '保持速度    ', '开始停车', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (118, '乘客怎样可以帮助驾驶员安全驾驶? ', '常询问路途,令驾驶员提⾼警觉 ', '打开收⾳机 ', '避免⽕爆与激励的谈话    ', '声量增⼤让他听到谈话内容', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (119, '此车辆可以 ', '在右边超车', '不准超车', '不准越线左转   ', '⼩⼼超车 ', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (120, '应急灯号亮着是怎样? ', '前后灯都闪亮  ', '后灯持久亮着', '前后灯持久亮着 ', '后灯闪亮 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (121, '在交通意外后,不应该做的是什么?', '讨论是谁的错', '写下证⼈的名字和地址', '画图列出时间地点和天⽓ ', '将车辆移开路⾯', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (122, '当听到警笛声或看见闪灯,你最好的做法是? ', '开往路边停下来', '在你当时的位置停下来 ', '倒车⾄路边停下来  ', '在前⾯路⼜转弯 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (123, '在不平坦的道路上跟随摩托车,你应该', '如同在正常道路上让出同样的空间,因为摩托车不受路⾯影响', '让出更远的空间,在摩托车避开路⾯坑洞会歪倒 ', '尽快超越摩托车 ', '与他靠近,让他在后视镜⾥看到你 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (124, '此标志意思是', '停车,安全时向前   ', '前⾯有停车标志,准备停车 ', '如有车辆靠近时停车', '停车,右转除外 ', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (125, '当有⼀辆车要插进你的前⾯,你应该 ', '慢下来并让出更⼤的空间 ', '保持速度和位置 ', '加速等那辆车路随你后', '驶离⾏车道 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (126, '当⼀辆学校巴⼠停在路旁并闪着红灯,你必须 ', '留意学童并准备停车', '停车等待红灯熄灭为⽌ ', '停车查看学童然后向前  ', '慢驶准备停车', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (127, '你不应该超越⼀辆车 ', '在双线⾼速公路', '⾯对电单车 ', '在恶劣天⽓', '当看不清楚时 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (128, '在雾天和夜间驾驶员应该减速和亮起 ', '泊车灯 ', '紧急灯号 ', '远光灯   ', '近光灯 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (129, 'a车将要左转,他的危险和视线受限于 ', '他的盲点 ', '卡车的后⾯和侧⾯', '直接跟在他后⾯的车辆', '在他右车道后的车辆 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (130, '此驾驶员在进⼊街道之前,他必须 ', '在⾏⼈道之前停车', '在便道之前停车 ', '如果没有⾏⼈的情况下开出马路 ', '慢驶并⼩⼼向前 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (131, '慢驶并⼩⼼向前 ', '轻踩刹车 ', '轻离油门并向前直驶', '使劲刹车', '赶快驶到路旁', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (132, '黄灯意思是', '停车,除⾮当时不安全 ', '停车安全时向前', '慢下来⼩⼼向前 ', '⼗字路口清晰时可以向前', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (133, '什么是”看-想-做”的正确策略', '他看到黄灯时他想’我可以穿过”,加速', '他看到卡车转弯时,他想’卡车不在我的道上’加速 ', '他看到卡车转弯时,他想’他可能转⼤弯’慢驶 ', '他看到卡车转弯时,他想’卡车和可能转⼤弯’突然停车', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (134, '摩托车将要左转,哪⼀辆车与它最没有危险?', '车辆a', '车辆c', '车辆d', '车辆b', 'd', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (135, '你为什么要特别⼩⼼摩托车 ', '因为警察经常使⽤摩托车', '摩托车永远有道路优先权 ', '摩托车体积⼤⼩,不容易被看见 ', '摩托车的速度⽐车辆快 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (136, '在夜间⼤部分车辆与⽕车相撞的原因是', '汽车驾驶员太疲倦 ', '驾驶员没看到⽕车', '⽕车驾驶员没有看到铁路上的车辆 ', '因为车辆卡在轨道上 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (137, '此标志意思是', '受⾏⼈控制的⾏⼈道,如果灯号闪亮时准备停车 ', '⾏⼈永远有道路优先权', '受⾏⼈控制的⾏⼈道,如果灯号亮着时准备停车', '在⾏⼈横过的前尽快离开', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (138, '汽车驾驶员常发觉 ', '骑摩托车⼈所配带头盔的类别可以判断他们的技术 ', '在判断摩托车速度时有困难 ', '可以很容易判断迎⾯⽽来的摩托车的速度 ', '可以与摩托车共同⼀条车道', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (139, '交通管理员的指⽰', '在于道路规则⽆冲突的情况下必须服从', '任何情况下必须服从', '不可以改变交通规则', '在公众道路上不需服从', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (140, '长途驾驶避免太累的最佳⽅法是', '携带⼀壶咖啡并多喝⼀点', '保持车辆温度 ', '计划你的⾏程必须包括休息,⽤餐和停车', '尽量多吃⼀些 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (141, '超越⼀辆⼤型卡车时,你应该', '从后视镜⾥看见被超越卡车的车头灯时才可以转回你的⾏车线', '在回到卡车和之前慢下来', '从后视镜看到被超越卡车驾驶员的车门,才可以回到原来的车线', '在回到列车道之前闪动远光灯 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (142, '桥梁及天桥', '它们的表⾯⽐路⾯更容易结冰 ', '不⽐其他路⾯滑', '冰雪更快融化     ', '它们冰雪⾯不是太滑', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (143, '要减轻交通意外的严重受伤,你应该', '系上腰部和肩部安全带', '系上腰部安全带 ', '抛出车外  ', '紧握⽅向盘', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (144, '保持车辆畅顺⾏驶的最好⽅法是', '沿途寻找有趣的东西', '常更换cd和磁带 ', '不停地使⽤⼿机与朋友联系以保持', '预测随时会发⽣的情况并计划应变', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (145, 'a车应该做的是什么', '打信号灯并移到左边 ', '慢驶,打信号灯并移到左边 ', '打信号灯,在必要时调整速度并找空间 ', '加速.打信号灯开始移到左 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (146, '倒车之前,驾驶员应该 ', '查看360度周围并回头向所倒的⽅向看去', '查看侧视镜并按响喇叭 ', '经过后视镜查看', '查看车后两次并依赖后视镜', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (147, '在市区,理想情况下跟随前⾯车辆的距离是', '1秒', '2秒', '4秒', '3秒', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (148, '什么情况之下司机应该按喇叭? ', '告诉他⼈他在附近', '给予警告的时候', '要超车的时候  ', '提醒其他道路使⽤者时', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (149, '此驾驶员应留下更多空间,原因是', '骑⾃⾏车的⼈可能慢下来', '骑⾃⾏车的⼈可能转弯', '骑⾃⾏车的⼈可能会换道 ', '骑⾃⾏车的⼈可能会下车', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (150, '在⼀个没有控制的⼗字路口,你应该', '响喇叭告诉其他驾驶员你在附近', '减速并查看危险', '保持速度,但是要查危险 ', '停车', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (151, '打滑的原因最有可能是 ', '车辆太旧', '路⾯太滑 ', '其他驾驶员突然停车', '驾驶技术差', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (152, '此标志意思是', '施⼯结束', '前⾯有施⼯ ', '前⾯有施⼯你必须掉头', '施⼯正展开', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (153, '交通灯号转为绿灯,驾驶员应该 ', '在进⼊路口之前按喇叭', '直接进⼊路口', '慢驶⾄路口并准备停车', '在开往⼗字路口前查看交通情况', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (154, '如果你的车头盖在⾏驶飞起来,你应该', '叫其他驾驶员替你盖上', '响喇叭并保持速度', '透过车头盖下边的缝隙向前看并尽快准备停车', '把脚离开油门', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (155, '在夜间驾驶要避免迎⾯车辆的灯光刺眼,最佳⽅法是 ', '亮起远光灯', '向马路的右边看', '闪烁远光灯告诉迎⾯驾驶员调暗灯光', '看着前⾯车辆', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (156, '在与迎⾯车辆距离多远应该转暗你的车头灯? ', '50公尺', '100公尺', '200公尺', '150公尺', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (157, '卡车周围的车辆应该格外⼩⼼,因为 ', '他的速度太慢', '卡车的盲点⽐较⼤', '他会突然停车', '你可能呼吸到废⽓ ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (158, '握⽅向盘最好的位置是', '左⼿8点钟和右⼿2点钟', '左⼿9点钟和右⼿4点钟 ', '左⼿10点钟和右⼿2点钟', '左⼿8点钟和右⼿5点钟', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (159, '响喇叭是', '提醒他⼈', '警告其他道路使⽤者', '告诉其他驾驶员你在附近', '通知他⼈让路', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (160, '在⾏驶时感觉太疲倦,你应该', '把⾳响调⼤声', '停车并⾛出车外休息 ', '不停地吃东西', '不停地唱歌⽽保持清醒', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (161, '因你的速度太慢⽽后⾯跟随着⼤队车辆,你最好的处理⽅法是', '加快速度', '驶⾄路边停下来让其他车辆先⾏ ', '移到右车道⾏驶', '保持速度继续向前', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (162, '在发⽣有⼈受伤的交通意外现场,你⾸先应该做的是 ', '打电话报警', '协助受伤⼈⼠ ', '通知保险公司', '打电话叫救护车 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (163, '在路边停车时,应距离路边 ', '15公分内', '20公分内', '30公分内', '40公分内', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (164, '有⼀辆车在你⾯前打着灯号左转,你应该', '响喇叭抗议', '减速或停车等他转过 ', '加速并绕过它', '转到右线⾏驶', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (165, '当有其他驾驶员向你做⽣⽓的⼿势,你应该', '同时对他做出⼿势', '不要⽤眼神去看他也不对他做任何⼿势 ', '转到其他⽅向 ', '打⼿提电话报警', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (166, '当⼗字路口亮着绿灯时,你什么时候可能通过', '没有⾏⼈时', '没有车辆堵塞时 ', '直接通过 ', '在畅通⽆阻的情况下 ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (167, '你想左转之前,应考虑的第⼀件事是', '亮着⽅⾯灯和回头看盲点', '判断迎⾯⽽来第⼀辆车后的速度与距离 ', '慢驶并准备停车', '尽快转弯', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (168, '在驾驶前情绪不稳定,你应该 ', '听⼀些轻松的⾳乐', '待情绪稳定下来才开车', '在驾驶之前深呼吸', '把精神集中起来', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (169, '圈中骑⾃⾏车的⼈,他将要', '停车', '左转', '右转 ', '直去', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (170, '图中的驾驶员,他将要 ', '停车', '左转', '右转', '直去 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (171, '图中的驾驶员,他将要', '慢车和和停车 ', '左转 ', '右转 ', '直去', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (172, '在下雪天要减低交通意外的发⽣,你最好的做法是', '换上雪胎', '常⽤刹车', '⼩⼼慢驶', '保持更远的距离', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (173, '⼤部分车辆容易在下雪天打滑,原因是', '速度太快', '刹车太急', '轮胎太旧没有线纹', '因为路⾯结冰', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (174, '在什么时候你必须亮着车头⾏车? ', '晚间 ', '任何时候 ', '黄昏后半⼩时⾄黎明前半⼩时', '黎明前半⼩时⾄黄昏前半⼩时', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (175, '在超越⼀辆车之后,什么时候可以回到你的⾏车道?', '等其他驾驶员挥⼿   ', '在安全的时候', '在后视镜啊完全看见被超越的车辆时', '在离开150公尺的时候 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (176, '使⽤减速线应该是 ', '在进⼊之前减速', '在进⼊之后减速 ', '保持速度', '加快速度 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (177, '马路上的⽩线是告诉你', '分开迎⾯车辆', '⼀条以上向同⽅向⾏驶的⾏车道', '不准换线', '可以换线', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (178, '图中的双黄线的意思是 ', '分隔迎⾯车辆', '你不可能越线⾏驶', '严禁超车 ', '不可以转弯 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (179, '图中的车辆', '车辆b可以⼩⼼超车', '车辆a可以⼩⼼超车 ', '不准越线⾏驶', '车辆b不可以超车', 'a', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (180, '什么时候你应该让路给公共汽车 ', '在住宅区', '在市区 ', '在任何时速不超过60公⾥的地⽅', '在⾼速公路上 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (181, '酒后驾驶的不良反应是什么? ', '常响喇叭', '经常改换⾏车道 ', '对距离及速度控制不稳定', '呼喝其他驾驶者 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (182, '在市区发⽣意外,你应在多长时间内报警', '24⼩时', '48⼩时', '72⼩时', '12⼩时 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (183, '紧急刹车的技巧是', '使劲刹车尽快把车停下', '尽快把车辆停下来⽽不锁死刹车制 ', '快速踩放刹车制  ', '响喇叭叫其他车辆离开 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (184, '图中哪⼀辆车在转弯时候摆晃⼒特别⼤ ', '车辆c ', '车辆a ', '车辆b', '车辆d ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (185, '什么时候汽车⾏可以与摩托车和公⽤⼀条车道', '在繁忙的市区', '永远不可以 ', '在单线车道上', '任何马路与⾼速公路', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (186, '你的车辆在⾏驶中爆胎,你⾸先该做的是 ', '紧握⽅向盘,并驶往路边停车', '突然刹车', '告诉其他驾驶者离开', '向滑⾏的反⽅⾯扭⽅向盘', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (187, '⼗字路⼜亮着红灯时,什么情况下可以左转', '在迎⾯没有车辆来的时候', '如果左转⽅向是单程路和没有路标禁⽌此转弯时', '任何时候', '在迎⾯车辆驾驶员挥⼿时候', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (188, '你必须泊车离开路口', '5公尺  ', '6公尺  ', '15公尺  ', '3公尺  ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (189, '你必须泊车离开消防龙头 ', '5公尺', '6公尺  ', '15公尺  ', '3公尺  ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (190, '学⽣交通队员在指挥交通时,你应该 ', '在上课时服从', '任何时候必须服从', '在不违反交通规则时服从', '慢下来安全向前', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (191, '骑⾃⾏车⼈⼠会出现在⾼速公路上', '任何时候', '永远不可以 ', '天⽓良好的时候 ', '在晚间 ', 'a', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (192, '⼗字路口有停车后标志,停车线和⾏⼈过路线,你必须把车停在', '停车标志前', '停车线之前 ', '⼈⾏道之前 ', '看到其他车辆的位置 ', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (193, '图中的⾏车道是⽤来 ', '公交车专⽤', '双程左转 ', '双程右转 ', '紧急车辆专⽤ ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (194, '红⾊车辆的驾驶员他应该 ', '响喇叭告诉前⾯的驾驶员他要超车', '⼩⼼迎⾯⽽来的车辆', '等过了弯路之后超车', '尽快超车 ', 'c', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (195, '为什么在⼤风的时候要离摩托车远些 ', '因为摩托车停车快', '因为狂风会将摩托车吹到你的车道上 ', '摩托车会使到你的旁避风 ', '摩托车的速度太慢', 'b', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (196, 'a车驾驶员应该 ', '响喇叭警告⾏⼈', '停车,让⾏⼈横过马路', '呼喝⾏⼈这⾥不是过路线', '闪亮灯号,告诉迎⾯车辆停车 ', 'b', '1');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (197, '你已⾏驶到最⾼限速⽽后⾯依然跟随⼤队车辆, 你最好的处理⽅法是', '保持速度继续⾏驶', '闪亮你的刹车灯', '移到右车道⾏驶', '驶⾄路旁停下来让其它车辆先⾏ ', 'd', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (198, '右转之前应该 ', '打信号灯和检查侧视镜 ', '打信号灯和检查所有倒后镜 ', '打信号灯,查看所有到后镜和回头看盲点     ', '如果没有⾏⼈尽快转弯 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (199, '驾驶的态度和风格', '每天都不同 ', '会受到情绪影响', '是⾃⼰选择的', '不会影响你的保险费 ', 'c', '0');
INSERT INTO `bcdrive` (`id`, `question`, `ans1`, `ans2`, `ans3`, `ans4`, `corr`, `image`) VALUES (200, '图中车辆谁应让路 ', '车辆a ', '车辆b ', '两部车可以同时转弯 ', '等候对⽅挥⼿⽰意 ', 'a', '1');
